import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import Header from '../components/header'
import Footer from '../components/footer'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TrevorJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Hi, Im Trevor.
        </h1>
        <h2 className={styles.h2}><Link href="/projects/projectsHome">Fullstack developer.</Link></h2>

        <p className={styles.description}>
          Preview some of my projects below or follow the links to view them live.
        </p>

        <div className={styles.grid}>
          {/* AudioSlate */}
          <a href="https://cgtones.github.io/Audioslate/" className={styles.card} target='blank'>
            <h2>AudioSlate &rarr;</h2>
            <iframe className={styles.projects} src='https://cgtones.github.io/Audioslate/'  width='100%' height='100%' />
            <p className={styles.description}>Utilizes the Spotify API to allow user to search for songs by album, artist, or song name & save to a custom playlist.
            </p>
          </a>

          {/* Ravenous */}
          <a href="https://cgtones.github.io/Ravenous/" className={styles.card} target='blank'>
            <h2>Ravenous &rarr;</h2>
            <iframe className={styles.projects} src='https://cgtones.github.io/Ravenous/'  width='100%' height='100%' />
            <p className={styles.description}>Utilizes the Yelp API to allow user to search for restaurants and businesses and see ratings and reviews.
            </p>
          </a>

          {/* Watch Party */}
          <a href="https://degengenesis.github.io/Film-Finder/" className={styles.card} target='blank'>
            <h2>Watch Party &rarr;</h2>
            <iframe className={styles.projects} src='https://degengenesis.github.io/Film-Finder/'  width='100%' height='100%' />
            <p className={styles.description}>Utilizes the The Movie Database API to allow users to search for movie or TV suggestions.
            </p>
          </a>

          {/* Excursion */}
          <a href="https://cgtones.github.io/excursion/" className={styles.card} target='blank'>
            <h2>Excursion &rarr;</h2>
            <iframe className={styles.projects} src='https://cgtones.github.io/excursion/'  width='100%' height='100%' />
            <p className={styles.description}>An app that suggests travel destinations based on your location.
            </p>
          </a>
        </div>
      </main>

      <Footer />
    </div>
  )
}
